### ISSUE TITLE
Error in Source

### ISSUE THREAD

**Issue by architkshk** [unbearab1e/FlattyTweet#2]
![irr](https://cloud.githubusercontent.com/assets/5001704/2642328/4ad0b8a8-bf07-11e3-8a14-2d11401248ea.png)

**Comment by unbearab1e** [comment]
Last commit should fix this.

**Comment by architkshk** [comment]
![error](https://cloud.githubusercontent.com/assets/5001704/2643357/482de798-bf1a-11e3-9527-c5698236d4b0.png)

**Comment by architkshk** [comment]
Please restore lines from 54 to 62 in the project to solve this error as i checked it.

**Comment by unbearab1e** [comment]
Last commit removed
