### ISSUE TITLE
Using Own twitter app

### ISSUE THREAD

**Issue by architkshk** [unbearab1e/FlattyTweet#3]
What to do in source code if i want to use my own twitter app api id?

**Comment by unbearab1e** [comment]
You can set it in settings 
![2014-04-09_164413](https://cloud.githubusercontent.com/assets/5321996/2654015/caed799e-bfcb-11e3-9401-411167941a77.png)
Also, check if your own twitter app settings is correct 
[Adding your own Twitter API keys](https://github.com/unbearab1e/FlattyTweet/wiki/Adding-your-own-Twitter-API-keys)
